events {
	
}

http {
	server {
		listen				443 ssl;
		server_name			localhost;
		ssl_certificate		inception_certif.crt;
		ssl_certificate_key	inception_private_key.key;
		proxy_ssl_protocols TLSv1.2 TLSv1.3;
		location ~ \.php {
			proxy_pass https://WordPress:9000;
		}
	}
}
