services:
  mariadb :
    secrets :
      mySqlPassword
      mySqlRootPassword
  wordpress :
  nginx :
    image : nginx
    port : 443

volumes:

networks:
  inception :
    dirver : bridge    
secrets:
  mySqlPassword:
    secrets/mySqlPassword.txt
  mySqlRootPassword:
    secrets/mySqlRootPassword.txt